# .streamlit/secrets.toml
[connections]
[connections.neondb]
url = "postgresql://neondb_owner:npg_syOZx7zMqag5@ep-wild-sun-acoe4vcq-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
OPENAI_API_KEY="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"
[postgres]
host = "ep-wild-sun-acoe4vcq-pooler.sa-east-1.aws.neon.tech"
port = 5432
dbname = "neondb"
user = "neondb_owner"
password = "npg_syOZx7zMqag5"